[versions]
agp = "8.6.1"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
appcompat = "1.7.0"
material = "1.12.0"
navVersion = "2.8.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navVersion"}
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navVersion"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
